/**
 * data.js - Guerilla Transformation Hacks
 * Datenbank für 34 Interventionen (nummeriert 1-34)
 */

const cardData = [
    { id: 1, title: "Strangey", image: "img/1.jpg", tags: ["Kommunikation", "Simplicity"], teaser: "Hier kommt die Kurzbeschreibung", text: "In einem Meeting wird etwas offen-sichtlich Irritierendes geäussert und keiner der Teilnehmer spricht es an. Hebt in solchen Situationen Strangy als digitale oder analoge Karte und diskutiert. Was ist hier gerade passiert? Wir fühls uns noch irritiert.", hintergrund: "", source: "Tem Toppings" },
    { id: 2, title: "Sprachbewusstsein", image: "img/2.jpg", tags: ["Ziel", "Kommunikation", "Team"], teaser: "Hier kommt die Kurzbeschreibung", text: "Ersetze heute jedes 'aber' durch ein 'und' Beispiel: ..., aber ich kann dies nicht tun weil → ..., und was kann ich tun das sich das ändert?", hintergrund: "Wir verändern von Innen, Haltung entscheidet", source: "" },
    { id: 3, title: "Neue Wege gehen", image: "img/3.jpg", tags: ["Schleudersitz", "Meetings", "Ziel"], teaser: "Hier kommt die Kurzbeschreibung", text: "Wähle heute einen ungewöhnlichen Weg zur Arbeit. Eröffnet neue Horizonte und die bringt dich an neue Orte.", hintergrund: "Wir verändern von Innen, Haltung entscheidet", source: "" },
    { id: 4, title: "Innehalten", image: "img/4.jpg", tags: ["Kommunikation", "Meetings"], teaser: "Hier kommt die Kurzbeschreibung", text: "Mache eine kurze Pause, bevor Du antwortest. Bei der Pause kurz reflektieren wo du deine Haltung sich gerade befindet", hintergrund: "Wir verändern von Innen, Haltung entscheidet", source: "" },
    { id: 5, title: "Der Nordstern", image: "img/5.jpg", tags: ["Team"], teaser: "Hier kommt die Kurzbeschreibung", text: "Mit OKR den Nordstern als Vision im Blick, der Weg dorthin kurzen Etappen. Die nächste Etappe planen und regelmässig den Karte prüfen ob wir noch auf dem richtigen Weg sind. Etappen Ziel erreicht? Dann die nächste Etappe planen", hintergrund: "OKR", source: "" },
    { id: 6, title: "Die Ausnahme-Regel", image: "img/6.jpg", tags: ["Kommunikation", "Schleudersitz", "Simplicity"], teaser: "Hier kommt die Kurzbeschreibung", text: "Ihr diskutiert ewig über einen Sonderfall? 'Aber was, wenn der Kunde aus Timbuktu anruft?' Stopp. Klärt erst den Standard. Wie läuft es in 90 Prozent der Fälle? Macht diesen Prozess so einfach wie möglich. Den komplizierten Sonderfall regelt ihr separat. Baut keine sechsspurige Autobahn für den einen Radfahrer, der sich verfahren hat.", hintergrund: "Hintergrund: Simplicity-Strategie #3 «Masse und Ausnahme trennen». Verhindert, dass Prozesse unnötig komplex werden, nur um seltene Ausnahmefälle standardmässig mit abzudecken.", source: "Simplicity" },
    { id: 7, title: "Der Kalender-Lügendetektor", image: "img/7.jpg", tags: ["Change", "Kommunikation", "Ziel"], teaser: "Hier kommt die Kurzbeschreibung", text: "Du sagst, Gesundheit ist dir wichtig? Oder Weiterbildung? Leg deinen Kalender daneben. Wo stehen diese Dinge? Wenn dein Kalender nicht zu deinen Werten passt, lügst du dich an. Trag die wichtigen privaten Dinge wie Geschäftstermine ein. Block die Zeit. Was nicht im Kalender steht, existiert in der Realität meistens nicht.", hintergrund: "Hintergrund: Abgleich von Werten und Aktivitäten aus 'Sinnovate your Life'. Dient dazu, die eigene Zeitverwendung (Ressource) mit den persönlichen Zielen und dem Sinnempfinden in Einklang zu bringen.", source: "Sinnovate your Life" },
    { id: 8, title: "Die Keep-it-simple Karte", image: "img/8.jpg", tags: ["Team", "Ziel", "Kommunikation"], teaser: "Hier kommt die Kurzbeschreibung", text: "'Wenn du es nicht einfach erklären kannst, hast du es noch nicht verstanden.' Beantwortet gemeinsam drei Fragen: 1 Was ist der Kern des Problems? 2 Was ist der eine wichtigste nächste Schritt? 3 Was können wir weglassen?", hintergrund: "Unser Gehirn neigt dazu, Dinge unnötig komplex zu machen. Klarheit entsteht nicht durch mehr Details, sondern durch bewusste Reduktion. Vereinfachung schafft Geschwindigkeit und bessere Entscheidungen.", source: "Vivienne" },
    { id: 9, title: "Struktur in der Einladung", image: "img/9.jpg", tags: ["Meetings", "Workshop", "Simplicity"], teaser: "Hier kommt die Kurzbeschreibung", text: "Meeting Canvas hilft dabei die Einladung zu strukturieren: - Ziele - Teilnehmer - Agenda - ToDo - Fakten - Erfolge - Learnings - Themenparkplatz", hintergrund: "", source: "Cornelia" },
    { id: 10, title: "Silent Start", image: "img/10.jpg", tags: ["Kommunikation", "Workshop"], teaser: "Hier kommt die Kurzbeschreibung", text: "Integriere in einen Workshop oder eine Sitzung am Anfang einen separaten Block für das Studium zum Thema vom Meeting/Workshop.", hintergrund: "", source: "Cornelia" },
    { id: 11, title: "Sitzungseinladungen die Lust machen", image: "img/11.jpg", tags: ["Meetings", "Change"], teaser: "Hier kommt die Kurzbeschreibung", text: "Schreibe auf die Einladung ein zum Thema passendes Zitat oder Bild. So schaffst die Bilder im Kopf auf die du beim Meeting referenzieren kannst.", hintergrund: "(", source: "Cornelia" },
    { id: 12, title: "Themenparkplatz", image: "img/12.jpg", tags: ["Simplicity", "Schleudersitz"], teaser: "Hier kommt die Kurzbeschreibung", text: "Damit Meetings pünktlich zum Ende kommen oder nicht passende Themen im Traktandum nicht verloren gehen – schaffe einen Themenparkplatz", hintergrund: "", source: "Cornelia" },
    { id: 13, title: "Life is better in Flip-Flops (MeetUP)", image: "img/13.jpg", tags: ["Simplicity", "Team", "Meetings"], teaser: "Hier kommt die Kurzbeschreibung", text: "Baue Sequenzen in ein Meeting ein in welchem du dir folgende Frage stellst: Was könnte/müssen wir tun um es noch schlechter zu werden / es noch schlechter zu tun. Diese Sabotage hilft den stockenden Denkprozess neu anzukurbeln.", hintergrund: "", source: "Cornelia" },
    { id: 14, title: "Die Uhr als Kompass", image: "img/14.jpg", tags: ["Workshop"], teaser: "Hier kommt die Kurzbeschreibung", text: "Installiere in jedem Sitzungszimmer eine Uhr welche für alle Teilnehmer gut sichtbar ist. Auch für Online-Meetings kann dieses Hilfsmittel eingesetzt werden", hintergrund: "", source: "Cornelia" },
    { id: 15, title: "Die Mini-Mut Karte", image: "img/15.jpg", tags: ["Meetings", "Ziel"], teaser: "Hier kommt die Kurzbeschreibung", text: "Setze dir oder setzt euch im Team eine kleine, unangenehme jedoch sinnvolle Aktion für die kommende Woche und erweitere so deine/eure Komfortzone.", hintergrund: "Wachstum entsteht selten durch grosse Revolutionen, sondern durch kleine mutige Schritte", source: "Vivienne" },
    { id: 16, title: "Das Future-You", image: "img/16.jpg", tags: ["Ziel", "Meetings"], teaser: "Hier kommt die Kurzbeschreibung", text: "Frage: 'Würde mein zukünftiges Ich diese Entscheidung feiern – oder bereuen?'", hintergrund: "Kurzfristige Impulse sabotieren langfristige Ziele", source: "Vivienne" },
    { id: 17, title: "Die Chaos-Notbremse", image: "img/17.jpg", tags: ["Change", "Ziel", "Team"], teaser: "Hier kommt die Kurzbeschreibung", text: "Zu viele Meinungen, zu viele To-dos, zu wenig Klarheit? Zeit für die Notbremse. Stoppt die Diskussion bewusst und stellt nur eine Frage: 'Was ist jetzt gerade der eine wichtigste nächste Schritt?' Erst wenn dieser klar ist, geht es weiter.", hintergrund: "Unter Stress versucht das Gehirn alles gleichzeitig zu lösen. Das führt zu Chaos statt Fortschritt. Klarheit entsteht durch Reduktion, ein Schritt nach dem anderen.", source: "Vivienne" },
    { id: 18, title: "Das Wir-statt-ich", image: "img/18.jpg", tags: ["Kommunikation", "Meetings"], teaser: "Hier kommt die Kurzbeschreibung", text: "Jede Person beantwortet: 'Was kann ich konkret beitragen, damit das Team erfolgreicher wird – nicht nur ich?' Ziel ist, Silodenken zu durchbrechen und Zusammenarbeit zu stärken.", hintergrund: "Teams scheitern selten an Kompetenz, sondern an Ego-Optimierung. Gemeinsamer Erfolg entsteht durch gegenseitige Unterstützung statt Einzelprofilierung.", source: "Vivienne" },
    { id: 19, title: "Der Werte-Spiegel", image: "img/19.jpg", tags: ["Meetings", "Change", "Schleudersitz"], teaser: "Hier kommt die Kurzbeschreibung", text: "Bei wichtigen Entscheidungen fragen: 'Welcher unserer Werte ist hier betroffen – und handeln wir im Einklang damit?'. Ziel ist, Entscheidungen an den definierten Team- oder Unternehmenswerten auszurichten.", hintergrund: "Werte sind nur dann relevant, wenn sie unter Druck Bestand haben. Ohne bewusste Reflexion werden sie schnell zu Wanddekoration.", source: "Vivienne" },
    { id: 20, title: "Der Perspektiven Check", image: "img/20.jpg", tags: ["Kommunikation", "Team", "Simplicity"], teaser: "Hier kommt die Kurzbeschreibung", text: "Vor finalen Entscheidungen wird explizit gefragt: 'Wer sieht das anders – und warum?'. Ziel ist, Konstruktive Kritik zu fördern", hintergrund: "Teams mit hoher psychologischer Sicherheit zeigen mehr Dissens – und treffen bessere Entscheidungen. Harmoniesucht führt oft zu schwachen Ergebnissen.", source: "Vivienne" },
    { id: 21, title: "Das Plus-Delta", image: "img/21.jpg", tags: ["Meetings"], teaser: "Hier kommt die Kurzbeschreibung", text: "Feedback erfolgt immer in zwei Schritten: 1. Plus (+): Was war hilfreich, stark oder wirkungsvoll? 2. Delta (Δ): Was könnte beim nächsten Mal anders oder noch besser sein? Ziel ist, Ausgewogenes, entwicklungsorientiertes Feedback zu fördern", hintergrund: "Reine Kritik erzeugt Abwehr; reines Lob verhindert Wachstum. Die Kombination aus Anerkennung und Entwicklung schafft Motivation und Lernbereitschaft.", source: "Vivienne" },
    { id: 22, title: "Der Storyteller", image: "img/22.jpg", tags: ["Schleudersitz", "Kommunikation", "Ziel"], teaser: "Hier kommt die Kurzbeschreibung", text: "Erkläre Veränderungen nicht nur mit Zahlen, sondern beantworte drei Fragen: 1. Warum ist Veränderung notwendig? 2. Was bedeutet sie konkret für uns? 3. Welche positive Zukunft entsteht dadurch? Die Mini-Formate 'Wir stehen vor ____, weil ____. Wenn wir das jetzt angehen, gewinnen wir ____. Und jeder von uns spielt dabei eine wichtige Rolle.' Ziel ist, Wandel verständlich, emotional greifbar und motivierend zu kommunizieren.", hintergrund: "Menschen folgen keiner PowerPoint, sie folgen einer Geschichte. Gute Storys reduzieren Unsicherheit, schaffen Orientierung und verbinden rationale Argumente mit emotionaler Bedeutung.", source: "Vivienne" },
    { id: 23, title: "Der synthetische Nörgler", image: "img/23.jpg", tags: ["Workshop", "Kommunikation", "Schleudersitz"], teaser: "Hier kommt die Kurzbeschreibung", text: "Keiner traut sich, deine Idee zu kritisieren? Alle sind zu höflich? Frag die KI. Sag ihr: 'Du bist eine skeptische Buchhalterin mit 20 Jahren Erfahrung. Zerpflück meinen Plan.' Die KI nimmt kein Blatt vor den Mund. Sie findet Lücken, die dein Team verschweigt. Nutze diese Kritik. Sie tut nicht weh, macht aber deinen Plan besser.", hintergrund: "Hintergrund: Nutzung von GenKI als Sparringspartner oder zur Simulation von Personas in der Testing-Phase des Design Thinkings, um Blind Spots zu identifizieren.", source: "Design Thinking mit KI" },
    { id: 24, title: "Die Zuversichts-Wette", image: "img/24.jpg", tags: ["Change", "Schleudersitz"], teaser: "Hier kommt die Kurzbeschreibung", text: "Frag dein Team bei Zielen nicht: 'Schaffen wir das?' Alle nicken brav. Frag lieber: 'Auf einer Skala von 0 bis 100, wie sicher seid ihr, dass wir das schaffen?' Bei 50 Prozent habt ihr ein Problem. Redet darüber. Was fehlt zur 100? Das macht vage Hoffnungen zu harten Fakten. Und deckt Risiken auf, bevor es knallt.", hintergrund: "Hintergrund: Das 'Confidence Level' im OKR-Prozess. Dient dazu, während der Umsetzung (im Check-in) frühzeitig Hindernisse zu erkennen und die Wahrscheinlichkeit der Zielerreichung realistisch einzuschätzen.", source: "OKR" },
    { id: 25, title: "Der 'Aha-Moment' / Der Elephant im Raum", image: "img/25.jpg", tags: ["Simplicity"], teaser: "Hier kommt die Kurzbeschreibung", text: "Mache eine Runde im Team und stellt auch bewusst die Frage 'Was hält uns auf, unser Ziel zu erreichen?' Denkt kurz individuell darüber nach und tauscht euch dann offen aus. Entdeckt gemeinsam eure Aha-Momente / eure Hindernisse, die Woche und das Projekt ruinieren. Und dann: Sucht gemeinsam nach Lösungen.", hintergrund: "Hintergrund: Probleme früh reflektieren, offen ansprechen und gemeinsam nach Lösungen suchen.", source: "" },
    { id: 26, title: "Die Rückwärts-Agenda", image: "img/26.jpg", tags: ["Team", "Schleudersitz", "Workshop"], teaser: "Hier kommt die Kurzbeschreibung", text: "Startet das Meeting mit der Beantwortung der Frage 'Wir müssen heute XX entscheiden, wie kommen wir dahin?'. Nach Beantwortung und Konsens, eruiert gemeinsam, welche Agenda, respektive Gesprächspunkte dafür relevant sind im entsprechenden Zeitrahmen.", hintergrund: "Hintergrund: Das Ziel von Entscheidungsmeetings ist unklar. Häufig wird unstrukturiert ein Gespräch geführt, ohne dass alle dasselbe Outcome vor Augen haben.", source: "Vivienne" },
    { id: 27, title: "Das Roundtable-Checkout", image: "img/27.jpg", tags: ["Simplicity", "Meetings"], teaser: "Hier kommt die Kurzbeschreibung", text: "Ziel eines Roundtable-Check-outs ist es, am Ende eines Meetings Klarheit über nächste Schritte zu schaffen, Verantwortlichkeiten zu stärken und sicherzustellen, dass alle Personen gehört werden. Durchgeführt wird er indem jede teilnehmende Person reihum in ein bis zwei Sätzen ihr wichtigstes Takeaway und ihren konkreten nächsten Schritt teilt.", hintergrund: "Meetings werden ohne klaren Abschluss oft ineffizient, da Verantwortlichkeiten und nächste Schritte unklar bleiben und insbesondere zurückhaltende Teilnehmende nicht ausreichend zu Wort kommen.", source: "Vivienne" },
    { id: 28, title: "Der Ego-Detektor", image: "img/28.jpg", tags: ["Kommunikation", "Change", "Schleudersitz"], teaser: "Hier kommt die Kurzbeschreibung", text: "Um blinde Flecken zu erkennen und unnötige Ego-Diskussionen zu vermeiden, stellt euch bei emotional werdenden Diskussionen folgende Frage: 'Geht es hier gerade ums Ziel, oder ums Recht haben?'", hintergrund: "Viele Konflikte entstehen nicht durch Inhalte, sondern durch Status, Rechthalten oder Verteidigungshaltung", source: "Vivienne" },
    { id: 29, title: "Der Gedanken Stopp", image: "img/30.jpg", tags: ["Kommunikation"], teaser: "Hier kommt die Kurzbeschreibung", text: "Schreibe das Problem auf und beantworte nur: 'Kann ich das heute konkret beeinflussen – ja oder nein?'", hintergrund: "Mentale Energy wird oft für Unkontrollierbares verschwendet", source: "Vivienne" },
    { id: 30, title: "Der Ideen Turbo", image: "img/31.jpg", tags: ["Simplicity", "Change", "Meetings"], teaser: "Hier kommt die Kurzbeschreibung", text: "Sucht ihr auf dem Schlauch punkto neuer Ideen? Dann beantwortet nacheinander drei Fragen: 1) 'Wie würde ein kompletter Anfänger das lösen?' 2) 'Was würde ein Konkurrent anders machen?' 3) 'Was wäre die radikale Lösung, wenn Geld und Angst keine Rolle spielen würden?'", hintergrund: "Unser Gehirn denkt in gewohnten Mustern. Kreativität entsteht nicht durch mehr Druck, sondern durch Perspektivwechsel und gedankliche Extreme. So werden kreative Blockaden gelöst und neue Denkansätze provoziert.", source: "Vivienne" },
    { id: 31, title: "Magischer Koffer", image: "img/32.jpg", tags: ["Ziel"], teaser: "Hier kommt die Kurzbeschreibung", text: "Als Check-IN Methode fürs Meeting verteilst du jedem Teilnehmer einen Alltagsgegenstand z.B. Kaffeetasse, WC Rolle etc. Jeder überlegt sich was der Gegenstand mit dem Thema zu tun hat.", hintergrund: "", source: "Cornelia / MeetUP" },
    { id: 32, title: "5x Warum", image: "img/33.jpg", tags: ["Workshop"], teaser: "Hier kommt die Kurzbeschreibung", text: "Die 5x Warum Methode ist ein wirkungsvolles Werkzeug zur Prozessoptimierung. Decke mit 5 mal 'Warum' die Ursachen von Ineffizienzen, Fehlern oder Verzögerungen in einem Prozess auf.", hintergrund: "", source: "Cornelia" },
    { id: 33, title: "Was stärkt unser Team", image: "img/34.jpg", tags: ["Ziel", "Team", "Simplicity"], teaser: "Hier kommt die Kurzbeschreibung", text: "Starte mit einer klaren Frage wie 'Was stärkt unser Team?'. Jede Person baut ein eigenes Modell, das ihre Sicht zeigt. Anschliessend erklärt jede*r das Modell und dessen Bedeutung. Danach erstellt ihr gemeinsam ein Teammodell, das die wichtigsten Elemente vereint. Diskutiert Zusammenhänge, Werte und mögliche Massnahmen. Zum Schluss reflektiert ihr, was ihr gelernt habt und wie ihr es im Alltag anwenden könnt.", hintergrund: "", source: "Cornelia / LEGO® Serious Play" },
    { id: 34, title: "Was stärkt unser Team (Prozess)", image: "img/35.jpg", tags: ["Schleudersitz", "Workshop"], teaser: "Hier kommt die Kurzbeschreibung", text: "Starte mit der Frage: 'Wie läuft unser Prozess heute ab?'. Jede Person baut ein Modell, das ihren Teil des Ist-Prozesses zeigt. Anschliessend erklärt jede*r das Modell und wichtige Herausforderungen. Stellt die Modelle zu einem gemeinsamen Prozessfluss zusammen. Identifiziert Engpässe, Risiken und fehlende Verbindungen. Baut danach Modelle für mögliche Verbesserungen. Verbindet diese zu einem Soll-Prozess. Leitet daraus konkrete Massnahmen, Verantwortliche und nächste Schritte ab.", hintergrund: "", source: "Cornelia / LEGO® Serious Play" }
];